// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatMessage } from "./ChatMessage";

export type AiGenerateRequest = { connectionId: string, prompt: string, currentQuery: string | null, currentTable: string | null, errorContext: string | null, conversationHistory: Array<ChatMessage> | null, };
