// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Capabilities = { 
/**
 * Accepts SQL text in `execute`.
 */
sql: boolean, 
/**
 * Groups collections under named schemas / databases / keyspaces.
 */
namespaces: boolean, 
/**
 * Has a stable column set per collection (false for schemaless documents).
 */
fixedColumns: boolean, 
/**
 * Supports offset paging in `fetch_page`.
 */
paging: boolean, 
/**
 * Can report an approximate row / key count cheaply.
 */
rowEstimate: boolean, 
/**
 * Distinguishes tables from views.
 */
views: boolean, };
