// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StagedChange } from "./StagedChange";

export type ChangesRequest = { connectionId: string, changes: Array<StagedChange>, };
