// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChangePreview = { statements: Array<string>, 
/**
 * The full script including the transaction wrapper, exactly as it will run.
 */
script: string, };
