// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConditionOp = "equals" | "not_equals" | "gt" | "gte" | "lt" | "lte" | "contains";
