// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectRequest = { id: string, 
/**
 * Session-only override of the saved database (sidebar switcher).
 */
database: string | null, };
