// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardVariable } from "./DashboardVariable";
import type { Widget } from "./Widget";

export type DashboardBody = { widgets: Array<Widget>, variables: Array<DashboardVariable>, refreshSeconds: number, };
