// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagramColumn } from "./DiagramColumn";

export type DiagramTable = { id: string, name: string, x: number, y: number, columns: Array<DiagramColumn>, };
