// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardBody } from "./DashboardBody";
import type { DiagramBody } from "./DiagramBody";
import type { WorkflowBody } from "./WorkflowBody";

export type DocumentBody = { "kind": "dashboard", "data": DashboardBody } | { "kind": "workflow", "data": WorkflowBody } | { "kind": "diagram", "data": DiagramBody };
