// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentBody } from "./DocumentBody";
import type { DocumentKind } from "./DocumentKind";

export type Document = { id: string, kind: DocumentKind, connectionId: string | null, name: string, body: DocumentBody, tags: Array<string>, createdAt: string, updatedAt: string, };
