// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorBuffer = { id: string, connectionId: string | null, title: string, content: string, updatedAt: string, };
