// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineKind } from "./EngineKind";
import type { FormKind } from "./FormKind";

export type EngineFacts = { kind: EngineKind, form: FormKind, defaultPort: number | null, };
