// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Engine = "postgres" | "mysql" | "mariadb" | "mssql" | "clickhouse" | "redis" | "mongodb" | "libsql" | "val_town" | "cloudflare_d1" | "supabase" | "planetscale" | "neon" | "sqlite";
