// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Engine = "postgres" | "mysql" | "mariadb" | "sqlite" | "clickhouse" | "redis" | "mongodb";
