// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineKind = "relational" | "document" | "key_value" | "wide_column" | "graph" | "time_series" | "vector" | "search" | "multi_model" | "spatial" | "in_memory" | "analytical" | "new_sql" | "embedded" | "ledger" | "streaming" | "object" | "hierarchical" | "network" | "xml" | "graph_vector" | "rdf";
