// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableRef } from "./TableRef";
import type { TransferFormat } from "./TransferFormat";

export type ExportRequest = { connectionId: string, tables: Array<TableRef>, format: TransferFormat, includeSchema: boolean, directory: string, maxRows: number | null, };
