// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportedFile } from "./ExportedFile";

export type ExportReport = { files: Array<ExportedFile>, elapsedMs: number, };
