// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableRef } from "./TableRef";

export type ExportedFile = { table: TableRef, path: string, rows: number, };
