// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForeignKey = { name: string, fromSchema: string | null, fromTable: string, fromColumns: Array<string>, toSchema: string | null, toTable: string, toColumns: Array<string>, };
