// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryOrigin } from "./HistoryOrigin";
import type { HistoryStatus } from "./HistoryStatus";

export type HistoryEntry = { id: number, connectionId: string, sql: string, status: HistoryStatus, origin: HistoryOrigin, error: string | null, elapsedMs: number, rowCount: number | null, executedAt: string, };
