// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableRef } from "./TableRef";
import type { TransferFormat } from "./TransferFormat";

export type ImportRequest = { connectionId: string, table: TableRef, path: string, format: TransferFormat, };
