// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterRule } from "./FilterRule";
import type { SortRule } from "./SortRule";

export type PageQuery = { sort: Array<SortRule>, filters: Array<FilterRule>, offset: number, limit: number, };
