// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnMeta } from "./ColumnMeta";
import type { Value } from "./Value";

export type ResultSet = { columns: Array<ColumnMeta>, rows: Array<Array<Value>>, truncated: boolean, };
