// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SavedQuery = { id: string, connectionId: string | null, name: string, sql: string, tags: Array<string>, createdAt: string, updatedAt: string, };
