// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppSettings } from "./AppSettings";

export type SaveSettingsRequest = { settings: AppSettings, 
/**
 * Some("") clears the sealed AI key; None keeps it; Some(key) replaces it.
 */
aiApiKey: string | null, };
