// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SchemaInfo } from "./SchemaInfo";

export type SchemaCatalog = { schemas: Array<SchemaInfo>, };
