// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CellValue } from "./CellValue";
import type { TableRef } from "./TableRef";
import type { Value } from "./Value";

export type StagedChange = { "kind": "update", id: string, table: TableRef, key: Array<CellValue>, column: string, old: Value, new: Value, } | { "kind": "insert", id: string, table: TableRef, values: Array<CellValue>, } | { "kind": "delete", id: string, table: TableRef, key: Array<CellValue>, };
