// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResultSet } from "./ResultSet";

export type StatementResult = { "kind": "rows", result: ResultSet, } | { "kind": "affected", rowsAffected: number, };
