// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageQuery } from "./PageQuery";
import type { TableRef } from "./TableRef";

export type TablePageRequest = { connectionId: string, table: TableRef, query: PageQuery, };
