// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableKind } from "./TableKind";

export type TableInfo = { schema: string | null, name: string, kind: TableKind, rowEstimate: number | null, };
