// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnInfo } from "./ColumnInfo";
import type { Value } from "./Value";

export type TablePage = { columns: Array<ColumnInfo>, rows: Array<Array<Value>>, offset: number, total: number | null, totalExact: boolean, };
