// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type Value = { "t": "null" } | { "t": "bool", "v": boolean } | { "t": "int", "v": number } | { "t": "float", "v": number } | { "t": "decimal", "v": string } | { "t": "text", "v": string } | { "t": "bytes", "v": string } | { "t": "json", "v": JsonValue } | { "t": "date_time", "v": string } | { "t": "unsupported", "v": string };
