// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WidgetKind = "area" | "line" | "bar" | "pie" | "sankey" | "table" | "metric" | "sparkline" | "map" | "progress" | "text" | "image" | "gif";
