// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetCondition } from "./WidgetCondition";
import type { WidgetKind } from "./WidgetKind";

export type Widget = { id: string, title: string, kind: WidgetKind, sql: string, x: number, y: number, w: number, h: number, tint: string | null, showChange: boolean, 
/**
 * Progress: the value that means 100 %.
 */
maxValue: number | null, 
/**
 * Text widgets: the body (no SQL).
 */
text: string | null, 
/**
 * Image / GIF widgets: the source URL.
 */
url: string | null, xLabel: string | null, yLabel: string | null, 
/**
 * Bar: horizontal bars.
 */
horizontal: boolean, 
/**
 * Progress: show percentage / raw values.
 */
showPercent: boolean, showValues: boolean, 
/**
 * Map: pulse the markers.
 */
pulse: boolean, 
/**
 * Metric / Text / Image / GIF: evaluated against the first cell of the first row; last match wins.
 */
conditions: Array<WidgetCondition>, };
