// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConditionOp } from "./ConditionOp";

export type WidgetCondition = { op: ConditionOp, value: string, 
/**
 * Text / image URL / tint name to use when the condition matches.
 */
content: string, };
