// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowStepResult = { stepId: string, name: string, ok: boolean, elapsedMs: number, rows: number | null, error: string | null, };
