// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowStep = { id: string, name: string, 
/**
 * None = the workflow's own connection.
 */
connectionId: string | null, sql: string, stopOnError: boolean, };
