// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowStepResult } from "./WorkflowStepResult";

export type WorkflowRunReport = { steps: Array<WorkflowStepResult>, stoppedEarly: boolean, };
